### ISSUE TITLE
Ability Modify sprite locations/size on screen.

### ISSUE THREAD

**Issue by footballdaddy** [nashkenazy/React-Visual-Novel#3]
First good job on the edits previously. Looks good.

One thing I can suggest now would be to add the ability to customize the way you show a sprite.
You should add a way to add custom styles: 
```
              <img
                key={props.sprite[0]}
                className="sprite first-sprite {props.customStyles}"
                src={props.sprite[0]}
              />
              <img
                key={props.sprite[1]}
                className="sprite second-sprite {props.customStyles}"
                src={props.sprite[1]}
              />

```
First I would suggest having the ability to add a custom classes for each sprite (this can be done with a simple variable added in classname).

Second, you should have might be good to have default sizes simple css should work for e.g. have grow, shrink, left, right, etc...

Lastly, I wouldn't know how to do this but it would but I would like to add more than one sprite. and customize them. 

Sprinkles might be adding customTextStyles for text as well.

**Comment by lettertea** [comment]
I've managed to get three sprites on the screen by adding a couple more properties (spriteLeft and spriteRight). It's still a bit buggy, but I think it'll work out in the end. I'll probably push the changes later this upcoming week. 

I haven't gotten to the other points, but they were things I was thinking about incorporating later (albeit in a slightly different manner than what you described). The CSS animations and effects might take a bit more time to incorporate due to some bugs the project has. I went through a bit of it yesterday, and I think it's doable. It'll just take a bit restructuring. 

As for the text styles, I'd probably make an options menu where the user can configure the sounds, text speed, text styles, and other potential stuff. I'm not sure when I'll get to it, and it'll depend on how much free time I have. But it's definitely in one of my checklists for this project.

I'll leave this issue open for now until the suggestions are resolved.

**Comment by lettertea** [comment]
Finally finished. The current master branch should reflect the updates. I recommend checking out the [sample site](https://rvn.netlify.com) as well as the README since they may address some other concerns. There were a few more changes other than the four you mentioned, but I'll address the four here.

1. You can use `spriteEffect`, `spriteLeftEffect`, and `spriteRightEffect` to add your CSS classes.
2. Preset effects are now shown in the [documentation](https://github.com/nashkenazy/React-Visual-Novel/blob/master/README.md#effect-properties).
3. `spriteLeft` and `spriteRight` are included now.
4. There are some fonts you can change into now in the Config menu. You can add more in [`ConfigMenu.js`](https://github.com/nashkenazy/React-Visual-Novel/blob/master/src/components/ConfigMenu.js).
